### ISSUE TITLE
configuring client ssl context 

### ISSUE THREAD

**Issue by henryw374** [lambdaisland/funnel-client#1]
With my setup I need to provide the funnel client with an ssl context. 

I have a way of doing this that gets things working. With this code: https://github.com/henryw374/funnel-client/commit/43fd2f9d8297092ea2c5ca48758ba4713c859c76 and by alter-var-rooting the new fn to return my context. 

This doesn't seem like a great way to configure it generally though. I am currently specifying the funnel uri via system property that funnel client uses. Although a similar thing, I cannot use that technique because system props can only be strings.

**Comment by plexus** [comment]
From this approach I'm guessing you're not calling the client API directly, but some other tool/library is calling it and you need to be able to configure the ssl context beforehand?

Perhaps we can make a system property that takes a var/function name? Something along the lines of

```clj
(some-> (System/getProperty "lambdaisland.funnel-client.ssl-context") symbol requiring-resolve deref (apply opts)))
```

**Comment by henryw374** [comment]
Yes, we are running tests using kaocha-cljs2, which is creating funnel client connection. 

The system property approach you suggest would work well in our case.

**Comment by alysbrooks** [comment]
@henryw374 Don't know if you saw, but #3 addresses this.
